### ISSUE TITLE
Dead link on devos.divnix.com

### ISSUE THREAD

**Issue by Seedscrapper** [divnix/devos#377] opened 2021-09-24 16:00 UTC
## Expected Behavior

In the https://devos.divnix.com/index.html#getting-started paragraph, the flake.nix link is redirecting to https://devos.divnix.com/flake.nix 

Should link to instead of https://github.com/divnix/devos/blob/master/flake.nix

## Current Behavior

404 page

## Possible Solution

Link to the right file flake.nix

## Steps to Reproduce

click :)

**Comment by nrdxp** [comment] 2021-09-24 16:42
essentially a duplicate of #372. Closing since these is just a part of the larger issue.

**Closed by nrdxp** 2021-09-24 16:42 UTC
Labels: bug

**Comment by Seedscrapper** [comment] 2021-09-24 17:20
I will be more vigilant in the future
