### ISSUE TITLE
Support darwin configuration workable

### ISSUE THREAD

**Issue by c4dr01d** [divnix/devos#129] opened 2021-02-18 09:57 UTC
**Is your feature request related to a problem? Please describe.**
I'm using Nix of my Macbook and my home workstation, I already merged my old nix config to devOS framework, now I'm trying merge my darwin config to devOS framework.

**Describe the solution you'd like**
Add darwin to framework, let framework can configure and manage darwin config easily.

**Describe alternatives you've considered**
I tried to write flake.nix to manage my nixOS and darwin config at one place, but I mess it up.

**Comment by nrdxp** [comment] 2021-02-18 15:32
I would love to improve darwin support, especially with the ongoing focus in the larger community, but I don't have a Mac. If we raise enough funds I'll gladly provision one in the cloud for building and development. On another note. This issue is a duplicate of #34, so we will track the issue there.

**Closed by nrdxp** 2021-02-18 15:32 UTC
Labels: enhancement
